# Generated by Django 3.0.7 on 2020-07-18 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='firstname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='contactno',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='lastname',
        ),
        migrations.AddField(
            model_name='signup',
            name='password2',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
